version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout 
      - run:
          name: Installing CLang
          command: 'apt-get install -y clang'
      - run:
          name: Install CMAKE
          command: 'apt-get install -y cmake'
      - run:
          name: Install Boost
          command: 'apt-get install -y Boost'
      - run:
          name: create build directory
          command: 'mkdir build && cd build'
      - run:
          name: Creating Build Files
          command: 'cmake ..'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './bin/point_test'