version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Make destination directory 1
          command: 'sudo mkdir /Chronos/' 
      - run:
          name: Make destination directory 2
          command: 'sudo mkdir /Chronos/libs/' 
      - run:
          name: Installing clang
          command: 'apt-get update && apt-get install -y clang'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Install BOOST
          command: 'apt-get update && apt-get install -y libboost-all-dev'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Pattern Matcher Unit Tests
          command: '/Chronos/Pattern-Matcher-Test --log_level=all'